-- CreateTable
CREATE TABLE `StripeEvent` (
  `id` VARCHAR(255) NOT NULL,
  `type` VARCHAR(120) NOT NULL,
  `processedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
