ALTER TABLE `BillingSyncLock` MODIFY `id` VARCHAR(255) NOT NULL;
ALTER TABLE `BillingConfig`
 ADD COLUMN `oneTimePriceId` VARCHAR(255) NOT NULL DEFAULT '',
 ADD COLUMN `oneTimeAmount` INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN `oneTimeEnabled` BOOLEAN NOT NULL DEFAULT false;
